"""Config autogeneration: ensure_config creates a starter config on first
run and warns about optional values an existing config omits."""

import json
from pathlib import Path

from xarness.config import DEFAULT_THEME, ensure_config, load_config


def test_missing_config_is_autogenerated(tmp_path: Path) -> None:
    path = tmp_path / "config.json"
    notices = ensure_config(path)
    assert len(notices) == 1 and "created starter config" in notices[0]
    data = json.loads(path.read_text())
    assert data["profiles"][0]["base_url"] == "https://api.openai.com/v1"
    assert data["profiles"][0]["model_id"] == "gpt-4.1"
    loaded = load_config(path)
    assert loaded.profile.model_id == "gpt-4.1"
    assert loaded.default_theme == DEFAULT_THEME


def test_existing_config_missing_optional_values_warns(tmp_path: Path) -> None:
    path = tmp_path / "config.json"
    path.write_text(json.dumps({
        "profiles": [{"name": "a", "base_url": "https://api.openai.com/v1",
                      "model_id": "m"}],
    }))
    notices = ensure_config(path)
    assert notices and "default_theme" in notices[0] and "container" in notices[0]
    assert "max_context" in notices[0]
    # The file is left untouched.
    assert "auto_compact_threshold" not in path.read_text()


def test_existing_config_complete_is_quiet(tmp_path: Path) -> None:
    path = tmp_path / "config.json"
    path.write_text(json.dumps({
        "default_theme": "one-light",
        "container": {"tool_output_limit": 4096},
        "profiles": [{
            "name": "a", "base_url": "https://api.openai.com/v1",
            "model_id": "m", "api_key_env": None, "shown_name": "M",
            "max_context": 1000, "cot_strength": "low", "keep_reasoning": True,
            "supports_vision": True, "auto_compact": True,
            "auto_compact_threshold": 0.5,
        }],
    }))
    assert ensure_config(path) == []


def test_malformed_existing_config_yields_no_notice(tmp_path: Path) -> None:
    path = tmp_path / "config.json"
    path.write_text("{not json")
    assert ensure_config(path) == []
